import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hooks</h1>
        <ul>
          <li>
            <Link href={"/use-state"}>useState</Link>
          </li>
          <li>
            <Link href={"/use-effect"}>useEffect</Link>
          </li>
          <li>
            <Link href={"/use-context"}>useContext</Link>
          </li>
          <li>
            <Link href={"/use-reducer"}>useReducer</Link>
          </li>
          <li>
            <Link href={"/use-memo"}>useMemo</Link>
          </li>
          <li>
            <Link href={"/use-callback"}>useCallback</Link>
          </li>
          <li>
            <Link href={"/use-ref"}>useRef</Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
