import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Card from "../components/Card";
import React, { useState } from "react";
import { LabelContext } from "../lib/context";

const UseStatePage: NextPage = () => {
  const [label, setLabel] = useState("dark");

  console.count("Render useContext");

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setLabel(e.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"/"}>
          <h1>useContext</h1>
        </Link>
        <input type="text" value={label} onChange={handleChange}></input>
        <LabelContext.Provider value={{ text: label }}>
          <Card></Card>
        </LabelContext.Provider>
      </main>
    </div>
  );
};

export default UseStatePage;
