import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import React, { useRef } from "react";

const UseRefPage: NextPage = () => {
  const openFile = useRef<HTMLInputElement>(null);
  console.count("Render useRef");

  const handleClick = () => {
    openFile.current?.click();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"/"}>
          <h1>useRef</h1>
        </Link>

        <button onClick={handleClick}>Open File</button>
        <input ref={openFile} type="file" style={{ display: "none" }}></input>
      </main>
    </div>
  );
};

export default UseRefPage;
