import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useEffect, useState } from "react";
import Counter from "../components/Counter";

const UseEffectPage: NextPage = () => {
  const [count1, setCount1] = useState(0);
  const [count2, setCount2] = useState(0);

  console.count("Render useEffect");

  useEffect(() => {
    console.log("Render Always");
  });

  useEffect(() => {
    console.log("Render Once");
  }, []);

  useEffect(() => {
    console.log("Render on Count 1");
  }, [count1]);

  useEffect(() => {
    console.log("Render on Count 2");
  }, [count2]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"/"}>
          <h1>useEffect</h1>
        </Link>

        <Counter count1={count1} count2={count2}></Counter>
        <button onClick={() => setCount1(count1 + 1)}>Add</button>
        <button onClick={() => setCount2(count2 + 1)}>Add</button>
      </main>
    </div>
  );
};

export default UseEffectPage;
