import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState, useCallback } from "react";
import Comment from "../components/Comment";

const UseCallbackPage: NextPage = () => {
  const [count1, setCount1] = useState(0);
  const [count2, setCount2] = useState(0);

  const handleClick1 = () => {
    setCount1((prevState) => prevState + 1);
  };

  const handleClick2 = () => {
    setCount2((prevState) => prevState + 1);
  };

  console.count("Render useState");

    const expensiveCalc = useCallback(
    (label: string) => {
      console.count("Too expensive");
      return `${label}: ${count1}`;
    },
    [count1]
  );

/*   const expensiveCalc = (label: string) => {
    console.count("Too expensive");
    return `${label}: ${count1}`;
  }; */

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"/"}>
          <h1>useCallback</h1>
        </Link>

        <p>Count 1: {count1}</p>
        <button onClick={handleClick1}>Add</button>

        <Comment func={expensiveCalc}></Comment>

        <p>Count 2: {count2}</p>
        <button onClick={handleClick2}>Add</button>
      </main>
    </div>
  );
};

export default UseCallbackPage;
